
[project]
name = "pyprotoparser"
version = "0.1.0"
description = "A Pure Python Protobuf 3 .proto Parser"
authors = [
    {name = "Chris Riccomini", email = "criccomini@apache.org"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
